version: '3.8'

services:
  app:
    build:
      context: .
      target: runner
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
